[theme]
base = "dark"                 # أو "light" لو عايزها فاتحة
primaryColor = "#137333"      # أخضر غامق (زي Looker)
backgroundColor = "#111418"   # خلفية غامقة للصفحة
secondaryBackgroundColor = "#1d242b"  # خلفية البانلز
textColor = "#ffffff"
